---

- name: restart Minecraft
  service:
    name: "{{ minecraft_server }}"
    state: restarted
  listen: restart_minecraft

- name: enable service
  service:
    name: "{{ item }}"
    state: started
    enabled: true
  with_items:
    - "{{ minecraft_server }}.service"
    - "{{ minecraft_server }}.socket"
  listen: enable_minecraft

- name: systemd reload
  systemd:
    daemon_reload: yes
  listen: reload_systemd
